parameters:
    chaplean_absence_io_client.api.url: 'https://app.absence.io/api/v2/'
    chaplean_absence_io_client.api.hawk_id: '%chaplean_absence_io_client.hawk_id%'
    chaplean_absence_io_client.api.hawk_key: '%chaplean_absence_io_client.hawk_key%'

services:
    absence_io_api:
        class: Chaplean\Bundle\AbsenceIoClientBundle\Api\AbsenceIoApi
        arguments:
            - '@guzzle.client.bonusly_api'
            - '@event_dispatcher'
            - '%chaplean_absence_io_client.api.url%'

    abscence_io_api.request_listener:
        class: Chaplean\Bundle\AbsenceIoClientBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: 'guzzle_bundle.pre_transaction', method: onPreTransaction, service: 'absence-io' }
        arguments:
            - '%chaplean_absence_io_client.api.url%'
            - '%chaplean_absence_io_client.api.hawk_id%'
            - '%chaplean_absence_io_client.api.hawk_key%'
